events {}

http {

    upstream frontend {
        server frontend:3000;
    }

    upstream flask {
        server flask:5000;
    }

    # Front
    server {
        listen 80;
        server_name front.loc;

        location / {
            proxy_pass http://frontend;
        }
    }

    # Laravel
    server {
        listen 80;
        server_name laravel.loc;

        location / {
            root /var/www/public;
            try_files $uri $uri/ /index.php?$query_string;
        }

        location ~ \.php$ {
            include fastcgi_params;
            fastcgi_pass laravel:9000;
            fastcgi_param SCRIPT_FILENAME /var/www/public$fastcgi_script_name;
        }
    }

    # Flask
    server {
        listen 80;
        server_name flask.loc;

        location / {
            proxy_pass http://flask;
        }
    }
}