upstream laravel_backend {
    server laravel:9000;
}

upstream python_backend {
    server python_api:8020;
}

server {
    listen 80;
    server_name localhost;
    root /var/www/public;
    index index.php;

    # Прокси для Python API (Астро-расчеты)
    location /api/natal/ {
        proxy_pass http://python_backend/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Основной Laravel + Inertia
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_pass laravel_backend;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
    }
}
