export const tarotNames = {
    fool: 'Шут',
    magician: 'Маг',
    priestess: 'Верховная Жрица',
    empress: 'Императрица',
    emperor: 'Император',
    hierophant: 'Иерофант',
    lovers: 'Влюблённые',
    chariot: 'Колесница',
    strength: 'Сила',
    hermit: 'Отшельник',
    fortune: 'Колесо Фортуны',
    justice: 'Справедливость',
    hanged: 'Повешенный',
    death: 'Смерть',
    temperance: 'Умеренность',
    devil: 'Дьявол',
    tower: 'Башня',
    star: 'Звезда',
    moon: 'Луна',
    sun: 'Солнце',
    judgement: 'Суд',
    world: 'Мир',
}
